apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: ay4u7opkq-nodejs 
  janus-idp.io/tekton: ay4u7opkq-nodejs
  backstage.io/kubernetes-id: ay4u7opkq-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ay4u7opkq-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml