apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ay4u7opkq-nodejs-gitops
  description: This is GitOps manifest for ay4u7opkq-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=ay4u7opkq-nodejs
    backstage.io/kubernetes-id: ay4u7opkq-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: ay4u7opkq-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ay4u7opkq-nodejs
