apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ay4u7opkq-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ay4u7opkq-nodejs 
  name: ay4u7opkq-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ay4u7opkq-nodejs 
